// todo_react/src/components/ToDo.js
import React, { useState } from 'react';
import Logo from '../assets/logo.svg';
import ToDoItem from './ToDoItem';
import './ToDo.css';
import { listenerCount } from 'cluster';

const ToDo = () => {

    const [list, setList] = useState([
        { id: 1, text: 'clean the house'},
        { id: 2, text: 'buy milk'}
    ]);
    const [toDo, setToDo] = useState("");

    const generateId = () => {
      if(list && list.length > 0){
        return( Math.max( ...list.map( (t) => t.id ) ) + 1 );
      }else{
        return 1;
      }
    };
    const createNewToDoItem = () => {
      if( !toDo ){
        alert('Please enter a todo!');
        return;
      }
      const newId = generateId();
      const newToDo = { id: newId, text: toDo };
      setList( [...list, newToDo] );
      setToDo("");
    };
    const handleKeyPress = (e) => {
      if( e.key === "Enter"){
        createNewToDoItem();
      }
    };
    const handleInput = (e) => {
      setToDo( e.target.value );
    };
    const deleteItem = () => {
      setList( list.filter( (item) => item.id !== id ) );
    };
    return (
        <div className='ToDo'>
          <img className='Logo' src={Logo} alt='React Logo' />
          <h1 className='ToDo-Header'> React To Do</h1>
          <div className='ToDo-Container'>
            <div className='ToDo-Content'>
              { list.map( (item) => {
                <ToDoItem key={item.id} item={item} deleteItem={deleteItem} />;
              })}
            </div>
            <div className='ToDo-Input'>
               <input type='text' value={toDo} onChange={handleInput} onKeyPress={handleKeyPress}  />
               <button className='ToDo-Add' onClick={createNewToDoItem}>+</button>
            </div>
          </div>
        </div>
    );

}

export default ToDo;

// todo_vue/src/components/ToDo.vue
<template>
  <div id='app'>
      <div class='ToDo'>
        <img class='Logo' :src='logo' alt='Vue Logo' />
        <h1 class='ToDo-Header'>Vue To Do</h1>
        <div class='ToDo-Container'>
          <ToDoItem v-for='item in list' :item='item' @delete='onDeleteItem' :key='item.id' />
        </div>
        <input type='text' v-model='todo' v-on:keyup.enter='createNewToDoItem' />
        <div class='ToDo-Add' @click='createNewToDoItem()'>+</div>
      </div>
  </div>  
</template>

<script>
import ToDoItem from './ToDoItem';
import Logo from '../assets/logo.png';
export default {
    name: 'to-do',
    components: {
        ToDoItem
    },
    data(){
      return {
          list: [{id: 1, text: 'clean the house'}, { id: 2, text: 'buy milk'}],
          todo: "",
          logo: Logo
      }
    },
    methods: {
        createNewToDoItem(){
            if(!this.todo){
              alert('Please Enter a ToDo!');
              return;
            }
            const newId = this.list.length ? Math.max.apply(null, this.list.map(t => t.id)) + 1 : 1;
            this.list.push( { id: newId, text: this.todo } );
            this.todo = '';
        },
        onDeleteItem(id){
            this.list = this.list.filter( item => item.id !== id );
        }
    } 

}
</script>

<style>
body {
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue, Helvetica,
    Arial, sans-serif;
  background: linear-gradient(#dcaeff, #ff6a3d);
  height: auto;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
}

.Logo {
  width: 50px;
  position: relative;
  top: 50px;
}

.ToDo {
  text-align: center;
  border: 1px solid white;
  width: 80vw;
  height: auto;
  box-shadow: 2px 2px 8px 0px rgba(0, 0, 0, 0.3);
  background: #fdfdfd;
  padding-bottom: 60px;
  margin: 40px auto;
}

.ToDo-Header {
  color: black;
  font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue, Helvetica,
    Arial, sans-serif;
  font-weight: 400;
  text-transform: uppercase;
  margin: 70px auto 30px;
}

.ToDo-Add {
  color: white;
  font-size: 2em;
  width: 0.5em;
  height: 0.5em;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 15px;
  cursor: pointer;
  background: #73ff73;
  border-radius: 10px;
  box-shadow: 1px 1px 1px #47a947;
  margin: 20px auto 0;
}

.ToDo-Add:hover {
  box-shadow: none;
  margin-top: 21px;
  margin-left: calc(auto + 1px);
}

.ToDo-Container {
  width: 80%;
  margin: 0 auto;
}

input {
  width: 60%;
  padding: 10px;
  font-size: 1em;
  margin: 10px auto;
  box-shadow: 1px 3px 20px 0px rgba(0, 0, 0, 0.3);
}

</style>
